// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,2,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	Pib                string                 `protobuf:"bytes,3,opt,name=pib,proto3" json:"pib,omitempty"`
	ActivityCode       string                 `protobuf:"bytes,4,opt,name=activity_code,json=activityCode,proto3" json:"activity_code,omitempty"`
	Address            string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompanyData) Reset() {
	*x = CompanyData{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyData) ProtoMessage() {}

func (x *CompanyData) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyData.ProtoReflect.Descriptor instead.
func (*CompanyData) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyData) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *CompanyData) GetPib() string {
	if x != nil {
		return x.Pib
	}
	return ""
}

func (x *CompanyData) GetActivityCode() string {
	if x != nil {
		return x.ActivityCode
	}
	return ""
}

func (x *CompanyData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccountType    string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	InitialBalance float64                `protobuf:"fixed64,4,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	AccountName    string                 `protobuf:"bytes,5,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	CreateCard     bool                   `protobuf:"varint,6,opt,name=create_card,json=createCard,proto3" json:"create_card,omitempty"`
	EmployeeId     int64                  `protobuf:"varint,7,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	CompanyData    *CompanyData           `protobuf:"bytes,8,opt,name=company_data,json=companyData,proto3" json:"company_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateAccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CreateAccountRequest) GetInitialBalance() float64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *CreateAccountRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CreateAccountRequest) GetCreateCard() bool {
	if x != nil {
		return x.CreateCard
	}
	return false
}

func (x *CreateAccountRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CreateAccountRequest) GetCompanyData() *CompanyData {
	if x != nil {
		return x.CompanyData
	}
	return nil
}

type AccountResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountName      string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	OwnerId          int64                  `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	EmployeeId       int64                  `protobuf:"varint,5,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	AccountType      string                 `protobuf:"bytes,7,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Status           string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Balance          float64                `protobuf:"fixed64,9,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,10,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	CreatedDate      string                 `protobuf:"bytes,11,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AccountResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *AccountResponse) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *AccountResponse) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *AccountResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *AccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountResponse) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountResponse) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountResponse       `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetAccount() *AccountResponse {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetMyAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyAccountsRequest) Reset() {
	*x = GetMyAccountsRequest{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyAccountsRequest) ProtoMessage() {}

func (x *GetMyAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyAccountsRequest.ProtoReflect.Descriptor instead.
func (*GetMyAccountsRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyAccountsRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type AccountSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountName      string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,4,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountSummary) Reset() {
	*x = AccountSummary{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSummary) ProtoMessage() {}

func (x *AccountSummary) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSummary.ProtoReflect.Descriptor instead.
func (*AccountSummary) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *AccountSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountSummary) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountSummary) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AccountSummary) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountSummary) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type GetMyAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountSummary      `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyAccountsResponse) Reset() {
	*x = GetMyAccountsResponse{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyAccountsResponse) ProtoMessage() {}

func (x *GetMyAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyAccountsResponse.ProtoReflect.Descriptor instead.
func (*GetMyAccountsResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *GetMyAccountsResponse) GetAccounts() []*AccountSummary {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetAccountRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type AccountDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountName      string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Owner            string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance          float64                `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,6,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	ReservedFunds    float64                `protobuf:"fixed64,7,opt,name=reserved_funds,json=reservedFunds,proto3" json:"reserved_funds,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,8,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Status           string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	AccountType      string                 `protobuf:"bytes,10,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	DailyLimit       float64                `protobuf:"fixed64,11,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit     float64                `protobuf:"fixed64,12,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	DailySpent       float64                `protobuf:"fixed64,13,opt,name=daily_spent,json=dailySpent,proto3" json:"daily_spent,omitempty"`
	MonthlySpent     float64                `protobuf:"fixed64,14,opt,name=monthly_spent,json=monthlySpent,proto3" json:"monthly_spent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountDetails) Reset() {
	*x = AccountDetails{}
	mi := &file_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetails) ProtoMessage() {}

func (x *AccountDetails) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetails.ProtoReflect.Descriptor instead.
func (*AccountDetails) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *AccountDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountDetails) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountDetails) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AccountDetails) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AccountDetails) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountDetails) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountDetails) GetReservedFunds() float64 {
	if x != nil {
		return x.ReservedFunds
	}
	return 0
}

func (x *AccountDetails) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *AccountDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountDetails) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *AccountDetails) GetDailyLimit() float64 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *AccountDetails) GetMonthlyLimit() float64 {
	if x != nil {
		return x.MonthlyLimit
	}
	return 0
}

func (x *AccountDetails) GetDailySpent() float64 {
	if x != nil {
		return x.DailySpent
	}
	return 0
}

func (x *AccountDetails) GetMonthlySpent() float64 {
	if x != nil {
		return x.MonthlySpent
	}
	return 0
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountDetails        `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountResponse) GetAccount() *AccountDetails {
	if x != nil {
		return x.Account
	}
	return nil
}

type RenameAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameAccountRequest) Reset() {
	*x = RenameAccountRequest{}
	mi := &file_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameAccountRequest) ProtoMessage() {}

func (x *RenameAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameAccountRequest.ProtoReflect.Descriptor instead.
func (*RenameAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{10}
}

func (x *RenameAccountRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RenameAccountRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *RenameAccountRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameAccountResponse) Reset() {
	*x = RenameAccountResponse{}
	mi := &file_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameAccountResponse) ProtoMessage() {}

func (x *RenameAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameAccountResponse.ProtoReflect.Descriptor instead.
func (*RenameAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{11}
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\aaccount\"\xa3\x01\n" +
	"\vCompanyData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x13registration_number\x18\x02 \x01(\tR\x12registrationNumber\x12\x10\n" +
	"\x03pib\x18\x03 \x01(\tR\x03pib\x12#\n" +
	"\ractivity_code\x18\x04 \x01(\tR\factivityCode\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"\xc2\x02\n" +
	"\x14CreateAccountRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\x12'\n" +
	"\x0finitial_balance\x18\x04 \x01(\x01R\x0einitialBalance\x12!\n" +
	"\faccount_name\x18\x05 \x01(\tR\vaccountName\x12\x1f\n" +
	"\vcreate_card\x18\x06 \x01(\bR\n" +
	"createCard\x12\x1f\n" +
	"\vemployee_id\x18\a \x01(\x03R\n" +
	"employeeId\x127\n" +
	"\fcompany_data\x18\b \x01(\v2\x14.account.CompanyDataR\vcompanyData\"\xf1\x02\n" +
	"\x0fAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId\x12\x1f\n" +
	"\vemployee_id\x18\x05 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\rcurrency_code\x18\x06 \x01(\tR\fcurrencyCode\x12!\n" +
	"\faccount_type\x18\a \x01(\tR\vaccountType\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x18\n" +
	"\abalance\x18\t \x01(\x01R\abalance\x12+\n" +
	"\x11available_balance\x18\n" +
	" \x01(\x01R\x10availableBalance\x12!\n" +
	"\fcreated_date\x18\v \x01(\tR\vcreatedDate\"K\n" +
	"\x15CreateAccountResponse\x122\n" +
	"\aaccount\x18\x01 \x01(\v2\x18.account.AccountResponseR\aaccount\"1\n" +
	"\x14GetMyAccountsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\"\xbc\x01\n" +
	"\x0eAccountSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12+\n" +
	"\x11available_balance\x18\x04 \x01(\x01R\x10availableBalance\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode\"L\n" +
	"\x15GetMyAccountsResponse\x123\n" +
	"\baccounts\x18\x01 \x03(\v2\x17.account.AccountSummaryR\baccounts\"M\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\"\xda\x03\n" +
	"\x0eAccountDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x01R\abalance\x12+\n" +
	"\x11available_balance\x18\x06 \x01(\x01R\x10availableBalance\x12%\n" +
	"\x0ereserved_funds\x18\a \x01(\x01R\rreservedFunds\x12#\n" +
	"\rcurrency_code\x18\b \x01(\tR\fcurrencyCode\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12!\n" +
	"\faccount_type\x18\n" +
	" \x01(\tR\vaccountType\x12\x1f\n" +
	"\vdaily_limit\x18\v \x01(\x01R\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\f \x01(\x01R\fmonthlyLimit\x12\x1f\n" +
	"\vdaily_spent\x18\r \x01(\x01R\n" +
	"dailySpent\x12#\n" +
	"\rmonthly_spent\x18\x0e \x01(\x01R\fmonthlySpent\"G\n" +
	"\x12GetAccountResponse\x121\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.account.AccountDetailsR\aaccount\"k\n" +
	"\x14RenameAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\"\x17\n" +
	"\x15RenameAccountResponse2\xc7\x02\n" +
	"\x0eAccountService\x12N\n" +
	"\rCreateAccount\x12\x1d.account.CreateAccountRequest\x1a\x1e.account.CreateAccountResponse\x12N\n" +
	"\rGetMyAccounts\x12\x1d.account.GetMyAccountsRequest\x1a\x1e.account.GetMyAccountsResponse\x12E\n" +
	"\n" +
	"GetAccount\x12\x1a.account.GetAccountRequest\x1a\x1b.account.GetAccountResponse\x12N\n" +
	"\rRenameAccount\x12\x1d.account.RenameAccountRequest\x1a\x1e.account.RenameAccountResponseB<Z:github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/accountb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_account_proto_goTypes = []any{
	(*CompanyData)(nil),           // 0: account.CompanyData
	(*CreateAccountRequest)(nil),  // 1: account.CreateAccountRequest
	(*AccountResponse)(nil),       // 2: account.AccountResponse
	(*CreateAccountResponse)(nil), // 3: account.CreateAccountResponse
	(*GetMyAccountsRequest)(nil),  // 4: account.GetMyAccountsRequest
	(*AccountSummary)(nil),        // 5: account.AccountSummary
	(*GetMyAccountsResponse)(nil), // 6: account.GetMyAccountsResponse
	(*GetAccountRequest)(nil),     // 7: account.GetAccountRequest
	(*AccountDetails)(nil),        // 8: account.AccountDetails
	(*GetAccountResponse)(nil),    // 9: account.GetAccountResponse
	(*RenameAccountRequest)(nil),  // 10: account.RenameAccountRequest
	(*RenameAccountResponse)(nil), // 11: account.RenameAccountResponse
}
var file_account_proto_depIdxs = []int32{
	0,  // 0: account.CreateAccountRequest.company_data:type_name -> account.CompanyData
	2,  // 1: account.CreateAccountResponse.account:type_name -> account.AccountResponse
	5,  // 2: account.GetMyAccountsResponse.accounts:type_name -> account.AccountSummary
	8,  // 3: account.GetAccountResponse.account:type_name -> account.AccountDetails
	1,  // 4: account.AccountService.CreateAccount:input_type -> account.CreateAccountRequest
	4,  // 5: account.AccountService.GetMyAccounts:input_type -> account.GetMyAccountsRequest
	7,  // 6: account.AccountService.GetAccount:input_type -> account.GetAccountRequest
	10, // 7: account.AccountService.RenameAccount:input_type -> account.RenameAccountRequest
	3,  // 8: account.AccountService.CreateAccount:output_type -> account.CreateAccountResponse
	6,  // 9: account.AccountService.GetMyAccounts:output_type -> account.GetMyAccountsResponse
	9,  // 10: account.AccountService.GetAccount:output_type -> account.GetAccountResponse
	11, // 11: account.AccountService.RenameAccount:output_type -> account.RenameAccountResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
