// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: email.proto

package email

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendActivationEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	ActivationLink string                 `protobuf:"bytes,3,opt,name=activation_link,json=activationLink,proto3" json:"activation_link,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendActivationEmailRequest) Reset() {
	*x = SendActivationEmailRequest{}
	mi := &file_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActivationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActivationEmailRequest) ProtoMessage() {}

func (x *SendActivationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActivationEmailRequest.ProtoReflect.Descriptor instead.
func (*SendActivationEmailRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendActivationEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendActivationEmailRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SendActivationEmailRequest) GetActivationLink() string {
	if x != nil {
		return x.ActivationLink
	}
	return ""
}

type SendActivationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActivationEmailResponse) Reset() {
	*x = SendActivationEmailResponse{}
	mi := &file_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActivationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActivationEmailResponse) ProtoMessage() {}

func (x *SendActivationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActivationEmailResponse.ProtoReflect.Descriptor instead.
func (*SendActivationEmailResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

type SendPasswordResetEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	ResetLink     string                 `protobuf:"bytes,3,opt,name=reset_link,json=resetLink,proto3" json:"reset_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPasswordResetEmailRequest) Reset() {
	*x = SendPasswordResetEmailRequest{}
	mi := &file_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetEmailRequest) ProtoMessage() {}

func (x *SendPasswordResetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetEmailRequest.ProtoReflect.Descriptor instead.
func (*SendPasswordResetEmailRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{2}
}

func (x *SendPasswordResetEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendPasswordResetEmailRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SendPasswordResetEmailRequest) GetResetLink() string {
	if x != nil {
		return x.ResetLink
	}
	return ""
}

type SendPasswordResetEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPasswordResetEmailResponse) Reset() {
	*x = SendPasswordResetEmailResponse{}
	mi := &file_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetEmailResponse) ProtoMessage() {}

func (x *SendPasswordResetEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetEmailResponse.ProtoReflect.Descriptor instead.
func (*SendPasswordResetEmailResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{3}
}

type SendAccountCreatedEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	AccountName   string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAccountCreatedEmailRequest) Reset() {
	*x = SendAccountCreatedEmailRequest{}
	mi := &file_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAccountCreatedEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAccountCreatedEmailRequest) ProtoMessage() {}

func (x *SendAccountCreatedEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAccountCreatedEmailRequest.ProtoReflect.Descriptor instead.
func (*SendAccountCreatedEmailRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{4}
}

func (x *SendAccountCreatedEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendAccountCreatedEmailRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SendAccountCreatedEmailRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *SendAccountCreatedEmailRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *SendAccountCreatedEmailRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type SendAccountCreatedEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAccountCreatedEmailResponse) Reset() {
	*x = SendAccountCreatedEmailResponse{}
	mi := &file_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAccountCreatedEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAccountCreatedEmailResponse) ProtoMessage() {}

func (x *SendAccountCreatedEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAccountCreatedEmailResponse.ProtoReflect.Descriptor instead.
func (*SendAccountCreatedEmailResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{5}
}

var File_email_proto protoreflect.FileDescriptor

const file_email_proto_rawDesc = "" +
	"\n" +
	"\vemail.proto\x12\x05email\"z\n" +
	"\x1aSendActivationEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12'\n" +
	"\x0factivation_link\x18\x03 \x01(\tR\x0eactivationLink\"\x1d\n" +
	"\x1bSendActivationEmailResponse\"s\n" +
	"\x1dSendPasswordResetEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1d\n" +
	"\n" +
	"reset_link\x18\x03 \x01(\tR\tresetLink\" \n" +
	"\x1eSendPasswordResetEmailResponse\"\xc4\x01\n" +
	"\x1eSendAccountCreatedEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode\"!\n" +
	"\x1fSendAccountCreatedEmailResponse2\xa5\x03\n" +
	"\fEmailService\x12\\\n" +
	"\x13SendActivationEmail\x12!.email.SendActivationEmailRequest\x1a\".email.SendActivationEmailResponse\x12e\n" +
	"\x16SendPasswordResetEmail\x12$.email.SendPasswordResetEmailRequest\x1a%.email.SendPasswordResetEmailResponse\x12f\n" +
	"\x1dSendPasswordConfirmationEmail\x12!.email.SendActivationEmailRequest\x1a\".email.SendActivationEmailResponse\x12h\n" +
	"\x17SendAccountCreatedEmail\x12%.email.SendAccountCreatedEmailRequest\x1a&.email.SendAccountCreatedEmailResponseB:Z8github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/emailb\x06proto3"

var (
	file_email_proto_rawDescOnce sync.Once
	file_email_proto_rawDescData []byte
)

func file_email_proto_rawDescGZIP() []byte {
	file_email_proto_rawDescOnce.Do(func() {
		file_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)))
	})
	return file_email_proto_rawDescData
}

var file_email_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_email_proto_goTypes = []any{
	(*SendActivationEmailRequest)(nil),      // 0: email.SendActivationEmailRequest
	(*SendActivationEmailResponse)(nil),     // 1: email.SendActivationEmailResponse
	(*SendPasswordResetEmailRequest)(nil),   // 2: email.SendPasswordResetEmailRequest
	(*SendPasswordResetEmailResponse)(nil),  // 3: email.SendPasswordResetEmailResponse
	(*SendAccountCreatedEmailRequest)(nil),  // 4: email.SendAccountCreatedEmailRequest
	(*SendAccountCreatedEmailResponse)(nil), // 5: email.SendAccountCreatedEmailResponse
}
var file_email_proto_depIdxs = []int32{
	0, // 0: email.EmailService.SendActivationEmail:input_type -> email.SendActivationEmailRequest
	2, // 1: email.EmailService.SendPasswordResetEmail:input_type -> email.SendPasswordResetEmailRequest
	0, // 2: email.EmailService.SendPasswordConfirmationEmail:input_type -> email.SendActivationEmailRequest
	4, // 3: email.EmailService.SendAccountCreatedEmail:input_type -> email.SendAccountCreatedEmailRequest
	1, // 4: email.EmailService.SendActivationEmail:output_type -> email.SendActivationEmailResponse
	3, // 5: email.EmailService.SendPasswordResetEmail:output_type -> email.SendPasswordResetEmailResponse
	1, // 6: email.EmailService.SendPasswordConfirmationEmail:output_type -> email.SendActivationEmailResponse
	5, // 7: email.EmailService.SendAccountCreatedEmail:output_type -> email.SendAccountCreatedEmailResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_email_proto_init() }
func file_email_proto_init() {
	if File_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_proto_goTypes,
		DependencyIndexes: file_email_proto_depIdxs,
		MessageInfos:      file_email_proto_msgTypes,
	}.Build()
	File_email_proto = out.File
	file_email_proto_goTypes = nil
	file_email_proto_depIdxs = nil
}
