// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: employee.proto

package employee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ime           string                 `protobuf:"bytes,2,opt,name=ime,proto3" json:"ime,omitempty"`
	Prezime       string                 `protobuf:"bytes,3,opt,name=prezime,proto3" json:"prezime,omitempty"`
	DatumRodjenja string                 `protobuf:"bytes,4,opt,name=datum_rodjenja,json=datumRodjenja,proto3" json:"datum_rodjenja,omitempty"`
	Pol           string                 `protobuf:"bytes,5,opt,name=pol,proto3" json:"pol,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	BrojTelefona  string                 `protobuf:"bytes,7,opt,name=broj_telefona,json=brojTelefona,proto3" json:"broj_telefona,omitempty"`
	Adresa        string                 `protobuf:"bytes,8,opt,name=adresa,proto3" json:"adresa,omitempty"`
	Username      string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	Pozicija      string                 `protobuf:"bytes,10,opt,name=pozicija,proto3" json:"pozicija,omitempty"`
	Departman     string                 `protobuf:"bytes,11,opt,name=departman,proto3" json:"departman,omitempty"`
	Aktivan       bool                   `protobuf:"varint,12,opt,name=aktivan,proto3" json:"aktivan,omitempty"`
	Dozvole       []string               `protobuf:"bytes,13,rep,name=dozvole,proto3" json:"dozvole,omitempty"`
	Jmbg          string                 `protobuf:"bytes,14,opt,name=jmbg,proto3" json:"jmbg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetIme() string {
	if x != nil {
		return x.Ime
	}
	return ""
}

func (x *Employee) GetPrezime() string {
	if x != nil {
		return x.Prezime
	}
	return ""
}

func (x *Employee) GetDatumRodjenja() string {
	if x != nil {
		return x.DatumRodjenja
	}
	return ""
}

func (x *Employee) GetPol() string {
	if x != nil {
		return x.Pol
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetBrojTelefona() string {
	if x != nil {
		return x.BrojTelefona
	}
	return ""
}

func (x *Employee) GetAdresa() string {
	if x != nil {
		return x.Adresa
	}
	return ""
}

func (x *Employee) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Employee) GetPozicija() string {
	if x != nil {
		return x.Pozicija
	}
	return ""
}

func (x *Employee) GetDepartman() string {
	if x != nil {
		return x.Departman
	}
	return ""
}

func (x *Employee) GetAktivan() bool {
	if x != nil {
		return x.Aktivan
	}
	return false
}

func (x *Employee) GetDozvole() []string {
	if x != nil {
		return x.Dozvole
	}
	return nil
}

func (x *Employee) GetJmbg() string {
	if x != nil {
		return x.Jmbg
	}
	return ""
}

type GetAllEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeesRequest) Reset() {
	*x = GetAllEmployeesRequest{}
	mi := &file_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeesRequest) ProtoMessage() {}

func (x *GetAllEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetAllEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllEmployeesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllEmployeesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeesResponse) Reset() {
	*x = GetAllEmployeesResponse{}
	mi := &file_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeesResponse) ProtoMessage() {}

func (x *GetAllEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeesResponse.ProtoReflect.Descriptor instead.
func (*GetAllEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *GetAllEmployeesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SearchEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ime           string                 `protobuf:"bytes,2,opt,name=ime,proto3" json:"ime,omitempty"`
	Prezime       string                 `protobuf:"bytes,3,opt,name=prezime,proto3" json:"prezime,omitempty"`
	Pozicija      string                 `protobuf:"bytes,4,opt,name=pozicija,proto3" json:"pozicija,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEmployeesRequest) Reset() {
	*x = SearchEmployeesRequest{}
	mi := &file_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEmployeesRequest) ProtoMessage() {}

func (x *SearchEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEmployeesRequest.ProtoReflect.Descriptor instead.
func (*SearchEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{3}
}

func (x *SearchEmployeesRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SearchEmployeesRequest) GetIme() string {
	if x != nil {
		return x.Ime
	}
	return ""
}

func (x *SearchEmployeesRequest) GetPrezime() string {
	if x != nil {
		return x.Prezime
	}
	return ""
}

func (x *SearchEmployeesRequest) GetPozicija() string {
	if x != nil {
		return x.Pozicija
	}
	return ""
}

func (x *SearchEmployeesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchEmployeesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEmployeesResponse) Reset() {
	*x = SearchEmployeesResponse{}
	mi := &file_employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEmployeesResponse) ProtoMessage() {}

func (x *SearchEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEmployeesResponse.ProtoReflect.Descriptor instead.
func (*SearchEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{4}
}

func (x *SearchEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *SearchEmployeesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetEmployeeCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeCredentialsRequest) Reset() {
	*x = GetEmployeeCredentialsRequest{}
	mi := &file_employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeCredentialsRequest) ProtoMessage() {}

func (x *GetEmployeeCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{5}
}

func (x *GetEmployeeCredentialsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetEmployeeCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Dozvole       []string               `protobuf:"bytes,3,rep,name=dozvole,proto3" json:"dozvole,omitempty"`
	Aktivan       bool                   `protobuf:"varint,4,opt,name=aktivan,proto3" json:"aktivan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeCredentialsResponse) Reset() {
	*x = GetEmployeeCredentialsResponse{}
	mi := &file_employee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeCredentialsResponse) ProtoMessage() {}

func (x *GetEmployeeCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{6}
}

func (x *GetEmployeeCredentialsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEmployeeCredentialsResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *GetEmployeeCredentialsResponse) GetDozvole() []string {
	if x != nil {
		return x.Dozvole
	}
	return nil
}

func (x *GetEmployeeCredentialsResponse) GetAktivan() bool {
	if x != nil {
		return x.Aktivan
	}
	return false
}

type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ime           string                 `protobuf:"bytes,1,opt,name=ime,proto3" json:"ime,omitempty"`
	Prezime       string                 `protobuf:"bytes,2,opt,name=prezime,proto3" json:"prezime,omitempty"`
	DatumRodjenja string                 `protobuf:"bytes,3,opt,name=datum_rodjenja,json=datumRodjenja,proto3" json:"datum_rodjenja,omitempty"`
	Pol           string                 `protobuf:"bytes,4,opt,name=pol,proto3" json:"pol,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	BrojTelefona  string                 `protobuf:"bytes,6,opt,name=broj_telefona,json=brojTelefona,proto3" json:"broj_telefona,omitempty"`
	Adresa        string                 `protobuf:"bytes,7,opt,name=adresa,proto3" json:"adresa,omitempty"`
	Username      string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Pozicija      string                 `protobuf:"bytes,9,opt,name=pozicija,proto3" json:"pozicija,omitempty"`
	Departman     string                 `protobuf:"bytes,10,opt,name=departman,proto3" json:"departman,omitempty"`
	Jmbg          string                 `protobuf:"bytes,11,opt,name=jmbg,proto3" json:"jmbg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_employee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEmployeeRequest) GetIme() string {
	if x != nil {
		return x.Ime
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPrezime() string {
	if x != nil {
		return x.Prezime
	}
	return ""
}

func (x *CreateEmployeeRequest) GetDatumRodjenja() string {
	if x != nil {
		return x.DatumRodjenja
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPol() string {
	if x != nil {
		return x.Pol
	}
	return ""
}

func (x *CreateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmployeeRequest) GetBrojTelefona() string {
	if x != nil {
		return x.BrojTelefona
	}
	return ""
}

func (x *CreateEmployeeRequest) GetAdresa() string {
	if x != nil {
		return x.Adresa
	}
	return ""
}

func (x *CreateEmployeeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPozicija() string {
	if x != nil {
		return x.Pozicija
	}
	return ""
}

func (x *CreateEmployeeRequest) GetDepartman() string {
	if x != nil {
		return x.Departman
	}
	return ""
}

func (x *CreateEmployeeRequest) GetJmbg() string {
	if x != nil {
		return x.Jmbg
	}
	return ""
}

type CreateEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeResponse) Reset() {
	*x = CreateEmployeeResponse{}
	mi := &file_employee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeResponse) ProtoMessage() {}

func (x *CreateEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeResponse.ProtoReflect.Descriptor instead.
func (*CreateEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{8}
}

func (x *CreateEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type GetEmployeeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIdRequest) Reset() {
	*x = GetEmployeeByIdRequest{}
	mi := &file_employee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIdRequest) ProtoMessage() {}

func (x *GetEmployeeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIdRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{9}
}

func (x *GetEmployeeByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEmployeeByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIdResponse) Reset() {
	*x = GetEmployeeByIdResponse{}
	mi := &file_employee_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIdResponse) ProtoMessage() {}

func (x *GetEmployeeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIdResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIdResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{10}
}

func (x *GetEmployeeByIdResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type UpdateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ime           string                 `protobuf:"bytes,2,opt,name=ime,proto3" json:"ime,omitempty"`
	Prezime       string                 `protobuf:"bytes,3,opt,name=prezime,proto3" json:"prezime,omitempty"`
	DatumRodjenja string                 `protobuf:"bytes,4,opt,name=datum_rodjenja,json=datumRodjenja,proto3" json:"datum_rodjenja,omitempty"`
	Pol           string                 `protobuf:"bytes,5,opt,name=pol,proto3" json:"pol,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	BrojTelefona  string                 `protobuf:"bytes,7,opt,name=broj_telefona,json=brojTelefona,proto3" json:"broj_telefona,omitempty"`
	Adresa        string                 `protobuf:"bytes,8,opt,name=adresa,proto3" json:"adresa,omitempty"`
	Username      string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	Pozicija      string                 `protobuf:"bytes,10,opt,name=pozicija,proto3" json:"pozicija,omitempty"`
	Departman     string                 `protobuf:"bytes,11,opt,name=departman,proto3" json:"departman,omitempty"`
	Aktivan       bool                   `protobuf:"varint,12,opt,name=aktivan,proto3" json:"aktivan,omitempty"`
	Dozvole       []string               `protobuf:"bytes,13,rep,name=dozvole,proto3" json:"dozvole,omitempty"`
	Jmbg          string                 `protobuf:"bytes,14,opt,name=jmbg,proto3" json:"jmbg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRequest) Reset() {
	*x = UpdateEmployeeRequest{}
	mi := &file_employee_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRequest) ProtoMessage() {}

func (x *UpdateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateEmployeeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmployeeRequest) GetIme() string {
	if x != nil {
		return x.Ime
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetPrezime() string {
	if x != nil {
		return x.Prezime
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetDatumRodjenja() string {
	if x != nil {
		return x.DatumRodjenja
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetPol() string {
	if x != nil {
		return x.Pol
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetBrojTelefona() string {
	if x != nil {
		return x.BrojTelefona
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetAdresa() string {
	if x != nil {
		return x.Adresa
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetPozicija() string {
	if x != nil {
		return x.Pozicija
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetDepartman() string {
	if x != nil {
		return x.Departman
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetAktivan() bool {
	if x != nil {
		return x.Aktivan
	}
	return false
}

func (x *UpdateEmployeeRequest) GetDozvole() []string {
	if x != nil {
		return x.Dozvole
	}
	return nil
}

func (x *UpdateEmployeeRequest) GetJmbg() string {
	if x != nil {
		return x.Jmbg
	}
	return ""
}

type UpdateEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeResponse) Reset() {
	*x = UpdateEmployeeResponse{}
	mi := &file_employee_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeResponse) ProtoMessage() {}

func (x *UpdateEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type ActivateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateEmployeeRequest) Reset() {
	*x = ActivateEmployeeRequest{}
	mi := &file_employee_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateEmployeeRequest) ProtoMessage() {}

func (x *ActivateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*ActivateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{13}
}

func (x *ActivateEmployeeRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *ActivateEmployeeRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type ActivateEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateEmployeeResponse) Reset() {
	*x = ActivateEmployeeResponse{}
	mi := &file_employee_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateEmployeeResponse) ProtoMessage() {}

func (x *ActivateEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateEmployeeResponse.ProtoReflect.Descriptor instead.
func (*ActivateEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{14}
}

type GetEmployeeByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByEmailRequest) Reset() {
	*x = GetEmployeeByEmailRequest{}
	mi := &file_employee_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByEmailRequest) ProtoMessage() {}

func (x *GetEmployeeByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByEmailRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{15}
}

func (x *GetEmployeeByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetEmployeeByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByEmailResponse) Reset() {
	*x = GetEmployeeByEmailResponse{}
	mi := &file_employee_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByEmailResponse) ProtoMessage() {}

func (x *GetEmployeeByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByEmailResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeByEmailResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{16}
}

func (x *GetEmployeeByEmailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEmployeeByEmailResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetEmployeeByEmailResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_employee_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePasswordRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *UpdatePasswordRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UpdatePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResponse) Reset() {
	*x = UpdatePasswordResponse{}
	mi := &file_employee_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResponse) ProtoMessage() {}

func (x *UpdatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{18}
}

var File_employee_proto protoreflect.FileDescriptor

const file_employee_proto_rawDesc = "" +
	"\n" +
	"\x0eemployee.proto\x12\bemployee\"\xf0\x02\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03ime\x18\x02 \x01(\tR\x03ime\x12\x18\n" +
	"\aprezime\x18\x03 \x01(\tR\aprezime\x12%\n" +
	"\x0edatum_rodjenja\x18\x04 \x01(\tR\rdatumRodjenja\x12\x10\n" +
	"\x03pol\x18\x05 \x01(\tR\x03pol\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12#\n" +
	"\rbroj_telefona\x18\a \x01(\tR\fbrojTelefona\x12\x16\n" +
	"\x06adresa\x18\b \x01(\tR\x06adresa\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x12\x1a\n" +
	"\bpozicija\x18\n" +
	" \x01(\tR\bpozicija\x12\x1c\n" +
	"\tdepartman\x18\v \x01(\tR\tdepartman\x12\x18\n" +
	"\aaktivan\x18\f \x01(\bR\aaktivan\x12\x18\n" +
	"\adozvole\x18\r \x03(\tR\adozvole\x12\x12\n" +
	"\x04jmbg\x18\x0e \x01(\tR\x04jmbg\"I\n" +
	"\x16GetAllEmployeesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"l\n" +
	"\x17GetAllEmployeesResponse\x120\n" +
	"\temployees\x18\x01 \x03(\v2\x12.employee.EmployeeR\temployees\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa7\x01\n" +
	"\x16SearchEmployeesRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03ime\x18\x02 \x01(\tR\x03ime\x12\x18\n" +
	"\aprezime\x18\x03 \x01(\tR\aprezime\x12\x1a\n" +
	"\bpozicija\x18\x04 \x01(\tR\bpozicija\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"l\n" +
	"\x17SearchEmployeesResponse\x120\n" +
	"\temployees\x18\x01 \x03(\v2\x12.employee.EmployeeR\temployees\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"5\n" +
	"\x1dGetEmployeeCredentialsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x89\x01\n" +
	"\x1eGetEmployeeCredentialsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x18\n" +
	"\adozvole\x18\x03 \x03(\tR\adozvole\x12\x18\n" +
	"\aaktivan\x18\x04 \x01(\bR\aaktivan\"\xb9\x02\n" +
	"\x15CreateEmployeeRequest\x12\x10\n" +
	"\x03ime\x18\x01 \x01(\tR\x03ime\x12\x18\n" +
	"\aprezime\x18\x02 \x01(\tR\aprezime\x12%\n" +
	"\x0edatum_rodjenja\x18\x03 \x01(\tR\rdatumRodjenja\x12\x10\n" +
	"\x03pol\x18\x04 \x01(\tR\x03pol\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12#\n" +
	"\rbroj_telefona\x18\x06 \x01(\tR\fbrojTelefona\x12\x16\n" +
	"\x06adresa\x18\a \x01(\tR\x06adresa\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x1a\n" +
	"\bpozicija\x18\t \x01(\tR\bpozicija\x12\x1c\n" +
	"\tdepartman\x18\n" +
	" \x01(\tR\tdepartman\x12\x12\n" +
	"\x04jmbg\x18\v \x01(\tR\x04jmbg\"H\n" +
	"\x16CreateEmployeeResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee\"(\n" +
	"\x16GetEmployeeByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x17GetEmployeeByIdResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee\"\xfd\x02\n" +
	"\x15UpdateEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03ime\x18\x02 \x01(\tR\x03ime\x12\x18\n" +
	"\aprezime\x18\x03 \x01(\tR\aprezime\x12%\n" +
	"\x0edatum_rodjenja\x18\x04 \x01(\tR\rdatumRodjenja\x12\x10\n" +
	"\x03pol\x18\x05 \x01(\tR\x03pol\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12#\n" +
	"\rbroj_telefona\x18\a \x01(\tR\fbrojTelefona\x12\x16\n" +
	"\x06adresa\x18\b \x01(\tR\x06adresa\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x12\x1a\n" +
	"\bpozicija\x18\n" +
	" \x01(\tR\bpozicija\x12\x1c\n" +
	"\tdepartman\x18\v \x01(\tR\tdepartman\x12\x18\n" +
	"\aaktivan\x18\f \x01(\bR\aaktivan\x12\x18\n" +
	"\adozvole\x18\r \x03(\tR\adozvole\x12\x12\n" +
	"\x04jmbg\x18\x0e \x01(\tR\x04jmbg\"H\n" +
	"\x16UpdateEmployeeResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee\"_\n" +
	"\x17ActivateEmployeeRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"\x1a\n" +
	"\x18ActivateEmployeeResponse\"1\n" +
	"\x19GetEmployeeByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"a\n" +
	"\x1aGetEmployeeByEmailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"]\n" +
	"\x15UpdatePasswordRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"\x18\n" +
	"\x16UpdatePasswordResponse2\xc1\x06\n" +
	"\x0fEmployeeService\x12V\n" +
	"\x0fGetAllEmployees\x12 .employee.GetAllEmployeesRequest\x1a!.employee.GetAllEmployeesResponse\x12V\n" +
	"\x0fSearchEmployees\x12 .employee.SearchEmployeesRequest\x1a!.employee.SearchEmployeesResponse\x12k\n" +
	"\x16GetEmployeeCredentials\x12'.employee.GetEmployeeCredentialsRequest\x1a(.employee.GetEmployeeCredentialsResponse\x12S\n" +
	"\x0eCreateEmployee\x12\x1f.employee.CreateEmployeeRequest\x1a .employee.CreateEmployeeResponse\x12V\n" +
	"\x0fGetEmployeeById\x12 .employee.GetEmployeeByIdRequest\x1a!.employee.GetEmployeeByIdResponse\x12S\n" +
	"\x0eUpdateEmployee\x12\x1f.employee.UpdateEmployeeRequest\x1a .employee.UpdateEmployeeResponse\x12Y\n" +
	"\x10ActivateEmployee\x12!.employee.ActivateEmployeeRequest\x1a\".employee.ActivateEmployeeResponse\x12_\n" +
	"\x12GetEmployeeByEmail\x12#.employee.GetEmployeeByEmailRequest\x1a$.employee.GetEmployeeByEmailResponse\x12S\n" +
	"\x0eUpdatePassword\x12\x1f.employee.UpdatePasswordRequest\x1a .employee.UpdatePasswordResponseB=Z;github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/employeeb\x06proto3"

var (
	file_employee_proto_rawDescOnce sync.Once
	file_employee_proto_rawDescData []byte
)

func file_employee_proto_rawDescGZIP() []byte {
	file_employee_proto_rawDescOnce.Do(func() {
		file_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_proto_rawDesc), len(file_employee_proto_rawDesc)))
	})
	return file_employee_proto_rawDescData
}

var file_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_employee_proto_goTypes = []any{
	(*Employee)(nil),                       // 0: employee.Employee
	(*GetAllEmployeesRequest)(nil),         // 1: employee.GetAllEmployeesRequest
	(*GetAllEmployeesResponse)(nil),        // 2: employee.GetAllEmployeesResponse
	(*SearchEmployeesRequest)(nil),         // 3: employee.SearchEmployeesRequest
	(*SearchEmployeesResponse)(nil),        // 4: employee.SearchEmployeesResponse
	(*GetEmployeeCredentialsRequest)(nil),  // 5: employee.GetEmployeeCredentialsRequest
	(*GetEmployeeCredentialsResponse)(nil), // 6: employee.GetEmployeeCredentialsResponse
	(*CreateEmployeeRequest)(nil),          // 7: employee.CreateEmployeeRequest
	(*CreateEmployeeResponse)(nil),         // 8: employee.CreateEmployeeResponse
	(*GetEmployeeByIdRequest)(nil),         // 9: employee.GetEmployeeByIdRequest
	(*GetEmployeeByIdResponse)(nil),        // 10: employee.GetEmployeeByIdResponse
	(*UpdateEmployeeRequest)(nil),          // 11: employee.UpdateEmployeeRequest
	(*UpdateEmployeeResponse)(nil),         // 12: employee.UpdateEmployeeResponse
	(*ActivateEmployeeRequest)(nil),        // 13: employee.ActivateEmployeeRequest
	(*ActivateEmployeeResponse)(nil),       // 14: employee.ActivateEmployeeResponse
	(*GetEmployeeByEmailRequest)(nil),      // 15: employee.GetEmployeeByEmailRequest
	(*GetEmployeeByEmailResponse)(nil),     // 16: employee.GetEmployeeByEmailResponse
	(*UpdatePasswordRequest)(nil),          // 17: employee.UpdatePasswordRequest
	(*UpdatePasswordResponse)(nil),         // 18: employee.UpdatePasswordResponse
}
var file_employee_proto_depIdxs = []int32{
	0,  // 0: employee.GetAllEmployeesResponse.employees:type_name -> employee.Employee
	0,  // 1: employee.SearchEmployeesResponse.employees:type_name -> employee.Employee
	0,  // 2: employee.CreateEmployeeResponse.employee:type_name -> employee.Employee
	0,  // 3: employee.GetEmployeeByIdResponse.employee:type_name -> employee.Employee
	0,  // 4: employee.UpdateEmployeeResponse.employee:type_name -> employee.Employee
	1,  // 5: employee.EmployeeService.GetAllEmployees:input_type -> employee.GetAllEmployeesRequest
	3,  // 6: employee.EmployeeService.SearchEmployees:input_type -> employee.SearchEmployeesRequest
	5,  // 7: employee.EmployeeService.GetEmployeeCredentials:input_type -> employee.GetEmployeeCredentialsRequest
	7,  // 8: employee.EmployeeService.CreateEmployee:input_type -> employee.CreateEmployeeRequest
	9,  // 9: employee.EmployeeService.GetEmployeeById:input_type -> employee.GetEmployeeByIdRequest
	11, // 10: employee.EmployeeService.UpdateEmployee:input_type -> employee.UpdateEmployeeRequest
	13, // 11: employee.EmployeeService.ActivateEmployee:input_type -> employee.ActivateEmployeeRequest
	15, // 12: employee.EmployeeService.GetEmployeeByEmail:input_type -> employee.GetEmployeeByEmailRequest
	17, // 13: employee.EmployeeService.UpdatePassword:input_type -> employee.UpdatePasswordRequest
	2,  // 14: employee.EmployeeService.GetAllEmployees:output_type -> employee.GetAllEmployeesResponse
	4,  // 15: employee.EmployeeService.SearchEmployees:output_type -> employee.SearchEmployeesResponse
	6,  // 16: employee.EmployeeService.GetEmployeeCredentials:output_type -> employee.GetEmployeeCredentialsResponse
	8,  // 17: employee.EmployeeService.CreateEmployee:output_type -> employee.CreateEmployeeResponse
	10, // 18: employee.EmployeeService.GetEmployeeById:output_type -> employee.GetEmployeeByIdResponse
	12, // 19: employee.EmployeeService.UpdateEmployee:output_type -> employee.UpdateEmployeeResponse
	14, // 20: employee.EmployeeService.ActivateEmployee:output_type -> employee.ActivateEmployeeResponse
	16, // 21: employee.EmployeeService.GetEmployeeByEmail:output_type -> employee.GetEmployeeByEmailResponse
	18, // 22: employee.EmployeeService.UpdatePassword:output_type -> employee.UpdatePasswordResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_employee_proto_init() }
func file_employee_proto_init() {
	if File_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_proto_rawDesc), len(file_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_proto_goTypes,
		DependencyIndexes: file_employee_proto_depIdxs,
		MessageInfos:      file_employee_proto_msgTypes,
	}.Build()
	File_employee_proto = out.File
	file_employee_proto_goTypes = nil
	file_employee_proto_depIdxs = nil
}
