// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: employee.proto

package employee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ime           string                 `protobuf:"bytes,2,opt,name=ime,proto3" json:"ime,omitempty"`
	Prezime       string                 `protobuf:"bytes,3,opt,name=prezime,proto3" json:"prezime,omitempty"`
	DatumRodjenja string                 `protobuf:"bytes,4,opt,name=datum_rodjenja,json=datumRodjenja,proto3" json:"datum_rodjenja,omitempty"`
	Pol           string                 `protobuf:"bytes,5,opt,name=pol,proto3" json:"pol,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	BrojTelefona  string                 `protobuf:"bytes,7,opt,name=broj_telefona,json=brojTelefona,proto3" json:"broj_telefona,omitempty"`
	Adresa        string                 `protobuf:"bytes,8,opt,name=adresa,proto3" json:"adresa,omitempty"`
	Username      string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	Pozicija      string                 `protobuf:"bytes,10,opt,name=pozicija,proto3" json:"pozicija,omitempty"`
	Departman     string                 `protobuf:"bytes,11,opt,name=departman,proto3" json:"departman,omitempty"`
	Aktivan       bool                   `protobuf:"varint,12,opt,name=aktivan,proto3" json:"aktivan,omitempty"`
	Dozvole       []string               `protobuf:"bytes,13,rep,name=dozvole,proto3" json:"dozvole,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetIme() string {
	if x != nil {
		return x.Ime
	}
	return ""
}

func (x *Employee) GetPrezime() string {
	if x != nil {
		return x.Prezime
	}
	return ""
}

func (x *Employee) GetDatumRodjenja() string {
	if x != nil {
		return x.DatumRodjenja
	}
	return ""
}

func (x *Employee) GetPol() string {
	if x != nil {
		return x.Pol
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetBrojTelefona() string {
	if x != nil {
		return x.BrojTelefona
	}
	return ""
}

func (x *Employee) GetAdresa() string {
	if x != nil {
		return x.Adresa
	}
	return ""
}

func (x *Employee) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Employee) GetPozicija() string {
	if x != nil {
		return x.Pozicija
	}
	return ""
}

func (x *Employee) GetDepartman() string {
	if x != nil {
		return x.Departman
	}
	return ""
}

func (x *Employee) GetAktivan() bool {
	if x != nil {
		return x.Aktivan
	}
	return false
}

func (x *Employee) GetDozvole() []string {
	if x != nil {
		return x.Dozvole
	}
	return nil
}

type GetAllEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeesRequest) Reset() {
	*x = GetAllEmployeesRequest{}
	mi := &file_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeesRequest) ProtoMessage() {}

func (x *GetAllEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetAllEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{1}
}

type GetAllEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeesResponse) Reset() {
	*x = GetAllEmployeesResponse{}
	mi := &file_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeesResponse) ProtoMessage() {}

func (x *GetAllEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeesResponse.ProtoReflect.Descriptor instead.
func (*GetAllEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

type SearchEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ime           string                 `protobuf:"bytes,2,opt,name=ime,proto3" json:"ime,omitempty"`
	Prezime       string                 `protobuf:"bytes,3,opt,name=prezime,proto3" json:"prezime,omitempty"`
	Pozicija      string                 `protobuf:"bytes,4,opt,name=pozicija,proto3" json:"pozicija,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEmployeesRequest) Reset() {
	*x = SearchEmployeesRequest{}
	mi := &file_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEmployeesRequest) ProtoMessage() {}

func (x *SearchEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEmployeesRequest.ProtoReflect.Descriptor instead.
func (*SearchEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{3}
}

func (x *SearchEmployeesRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SearchEmployeesRequest) GetIme() string {
	if x != nil {
		return x.Ime
	}
	return ""
}

func (x *SearchEmployeesRequest) GetPrezime() string {
	if x != nil {
		return x.Prezime
	}
	return ""
}

func (x *SearchEmployeesRequest) GetPozicija() string {
	if x != nil {
		return x.Pozicija
	}
	return ""
}

type SearchEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEmployeesResponse) Reset() {
	*x = SearchEmployeesResponse{}
	mi := &file_employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEmployeesResponse) ProtoMessage() {}

func (x *SearchEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEmployeesResponse.ProtoReflect.Descriptor instead.
func (*SearchEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{4}
}

func (x *SearchEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

type GetEmployeeCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeCredentialsRequest) Reset() {
	*x = GetEmployeeCredentialsRequest{}
	mi := &file_employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeCredentialsRequest) ProtoMessage() {}

func (x *GetEmployeeCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{5}
}

func (x *GetEmployeeCredentialsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetEmployeeCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Dozvole       []string               `protobuf:"bytes,3,rep,name=dozvole,proto3" json:"dozvole,omitempty"`
	Aktivan       bool                   `protobuf:"varint,4,opt,name=aktivan,proto3" json:"aktivan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeCredentialsResponse) Reset() {
	*x = GetEmployeeCredentialsResponse{}
	mi := &file_employee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeCredentialsResponse) ProtoMessage() {}

func (x *GetEmployeeCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{6}
}

func (x *GetEmployeeCredentialsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEmployeeCredentialsResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *GetEmployeeCredentialsResponse) GetDozvole() []string {
	if x != nil {
		return x.Dozvole
	}
	return nil
}

func (x *GetEmployeeCredentialsResponse) GetAktivan() bool {
	if x != nil {
		return x.Aktivan
	}
	return false
}

type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ime           string                 `protobuf:"bytes,1,opt,name=ime,proto3" json:"ime,omitempty"`
	Prezime       string                 `protobuf:"bytes,2,opt,name=prezime,proto3" json:"prezime,omitempty"`
	DatumRodjenja string                 `protobuf:"bytes,3,opt,name=datum_rodjenja,json=datumRodjenja,proto3" json:"datum_rodjenja,omitempty"`
	Pol           string                 `protobuf:"bytes,4,opt,name=pol,proto3" json:"pol,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	BrojTelefona  string                 `protobuf:"bytes,6,opt,name=broj_telefona,json=brojTelefona,proto3" json:"broj_telefona,omitempty"`
	Adresa        string                 `protobuf:"bytes,7,opt,name=adresa,proto3" json:"adresa,omitempty"`
	Username      string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Pozicija      string                 `protobuf:"bytes,9,opt,name=pozicija,proto3" json:"pozicija,omitempty"`
	Departman     string                 `protobuf:"bytes,10,opt,name=departman,proto3" json:"departman,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_employee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEmployeeRequest) GetIme() string {
	if x != nil {
		return x.Ime
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPrezime() string {
	if x != nil {
		return x.Prezime
	}
	return ""
}

func (x *CreateEmployeeRequest) GetDatumRodjenja() string {
	if x != nil {
		return x.DatumRodjenja
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPol() string {
	if x != nil {
		return x.Pol
	}
	return ""
}

func (x *CreateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmployeeRequest) GetBrojTelefona() string {
	if x != nil {
		return x.BrojTelefona
	}
	return ""
}

func (x *CreateEmployeeRequest) GetAdresa() string {
	if x != nil {
		return x.Adresa
	}
	return ""
}

func (x *CreateEmployeeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPozicija() string {
	if x != nil {
		return x.Pozicija
	}
	return ""
}

func (x *CreateEmployeeRequest) GetDepartman() string {
	if x != nil {
		return x.Departman
	}
	return ""
}

type CreateEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeResponse) Reset() {
	*x = CreateEmployeeResponse{}
	mi := &file_employee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeResponse) ProtoMessage() {}

func (x *CreateEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeResponse.ProtoReflect.Descriptor instead.
func (*CreateEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{8}
}

func (x *CreateEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type GetEmployeeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIdRequest) Reset() {
	*x = GetEmployeeByIdRequest{}
	mi := &file_employee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIdRequest) ProtoMessage() {}

func (x *GetEmployeeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIdRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{9}
}

func (x *GetEmployeeByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEmployeeByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIdResponse) Reset() {
	*x = GetEmployeeByIdResponse{}
	mi := &file_employee_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIdResponse) ProtoMessage() {}

func (x *GetEmployeeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIdResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIdResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{10}
}

func (x *GetEmployeeByIdResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

var File_employee_proto protoreflect.FileDescriptor

const file_employee_proto_rawDesc = "" +
	"\n" +
	"\x0eemployee.proto\x12\bemployee\"\xdc\x02\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03ime\x18\x02 \x01(\tR\x03ime\x12\x18\n" +
	"\aprezime\x18\x03 \x01(\tR\aprezime\x12%\n" +
	"\x0edatum_rodjenja\x18\x04 \x01(\tR\rdatumRodjenja\x12\x10\n" +
	"\x03pol\x18\x05 \x01(\tR\x03pol\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12#\n" +
	"\rbroj_telefona\x18\a \x01(\tR\fbrojTelefona\x12\x16\n" +
	"\x06adresa\x18\b \x01(\tR\x06adresa\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x12\x1a\n" +
	"\bpozicija\x18\n" +
	" \x01(\tR\bpozicija\x12\x1c\n" +
	"\tdepartman\x18\v \x01(\tR\tdepartman\x12\x18\n" +
	"\aaktivan\x18\f \x01(\bR\aaktivan\x12\x18\n" +
	"\adozvole\x18\r \x03(\tR\adozvole\"\x18\n" +
	"\x16GetAllEmployeesRequest\"K\n" +
	"\x17GetAllEmployeesResponse\x120\n" +
	"\temployees\x18\x01 \x03(\v2\x12.employee.EmployeeR\temployees\"v\n" +
	"\x16SearchEmployeesRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03ime\x18\x02 \x01(\tR\x03ime\x12\x18\n" +
	"\aprezime\x18\x03 \x01(\tR\aprezime\x12\x1a\n" +
	"\bpozicija\x18\x04 \x01(\tR\bpozicija\"K\n" +
	"\x17SearchEmployeesResponse\x120\n" +
	"\temployees\x18\x01 \x03(\v2\x12.employee.EmployeeR\temployees\";\n" +
	"\x1dGetEmployeeCredentialsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x89\x01\n" +
	"\x1eGetEmployeeCredentialsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x18\n" +
	"\adozvole\x18\x03 \x03(\tR\adozvole\x12\x18\n" +
	"\aaktivan\x18\x04 \x01(\bR\aaktivan\"\xa5\x02\n" +
	"\x15CreateEmployeeRequest\x12\x10\n" +
	"\x03ime\x18\x01 \x01(\tR\x03ime\x12\x18\n" +
	"\aprezime\x18\x02 \x01(\tR\aprezime\x12%\n" +
	"\x0edatum_rodjenja\x18\x03 \x01(\tR\rdatumRodjenja\x12\x10\n" +
	"\x03pol\x18\x04 \x01(\tR\x03pol\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12#\n" +
	"\rbroj_telefona\x18\x06 \x01(\tR\fbrojTelefona\x12\x16\n" +
	"\x06adresa\x18\a \x01(\tR\x06adresa\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x1a\n" +
	"\bpozicija\x18\t \x01(\tR\bpozicija\x12\x1c\n" +
	"\tdepartman\x18\n" +
	" \x01(\tR\tdepartman\"H\n" +
	"\x16CreateEmployeeResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee\"(\n" +
	"\x16GetEmployeeByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x17GetEmployeeByIdResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee2\xdb\x03\n" +
	"\x0fEmployeeService\x12V\n" +
	"\x0fGetAllEmployees\x12 .employee.GetAllEmployeesRequest\x1a!.employee.GetAllEmployeesResponse\x12V\n" +
	"\x0fSearchEmployees\x12 .employee.SearchEmployeesRequest\x1a!.employee.SearchEmployeesResponse\x12k\n" +
	"\x16GetEmployeeCredentials\x12'.employee.GetEmployeeCredentialsRequest\x1a(.employee.GetEmployeeCredentialsResponse\x12S\n" +
	"\x0eCreateEmployee\x12\x1f.employee.CreateEmployeeRequest\x1a .employee.CreateEmployeeResponse\x12V\n" +
	"\x0fGetEmployeeById\x12 .employee.GetEmployeeByIdRequest\x1a!.employee.GetEmployeeByIdResponseB/Z-github.com/exbanka/backend/shared/pb/employeeb\x06proto3"

var (
	file_employee_proto_rawDescOnce sync.Once
	file_employee_proto_rawDescData []byte
)

func file_employee_proto_rawDescGZIP() []byte {
	file_employee_proto_rawDescOnce.Do(func() {
		file_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_proto_rawDesc), len(file_employee_proto_rawDesc)))
	})
	return file_employee_proto_rawDescData
}

var file_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_employee_proto_goTypes = []any{
	(*Employee)(nil),                       // 0: employee.Employee
	(*GetAllEmployeesRequest)(nil),         // 1: employee.GetAllEmployeesRequest
	(*GetAllEmployeesResponse)(nil),        // 2: employee.GetAllEmployeesResponse
	(*SearchEmployeesRequest)(nil),         // 3: employee.SearchEmployeesRequest
	(*SearchEmployeesResponse)(nil),        // 4: employee.SearchEmployeesResponse
	(*GetEmployeeCredentialsRequest)(nil),  // 5: employee.GetEmployeeCredentialsRequest
	(*GetEmployeeCredentialsResponse)(nil), // 6: employee.GetEmployeeCredentialsResponse
	(*CreateEmployeeRequest)(nil),          // 7: employee.CreateEmployeeRequest
	(*CreateEmployeeResponse)(nil),         // 8: employee.CreateEmployeeResponse
	(*GetEmployeeByIdRequest)(nil),         // 9: employee.GetEmployeeByIdRequest
	(*GetEmployeeByIdResponse)(nil),        // 10: employee.GetEmployeeByIdResponse
}
var file_employee_proto_depIdxs = []int32{
	0,  // 0: employee.GetAllEmployeesResponse.employees:type_name -> employee.Employee
	0,  // 1: employee.SearchEmployeesResponse.employees:type_name -> employee.Employee
	0,  // 2: employee.CreateEmployeeResponse.employee:type_name -> employee.Employee
	0,  // 3: employee.GetEmployeeByIdResponse.employee:type_name -> employee.Employee
	1,  // 4: employee.EmployeeService.GetAllEmployees:input_type -> employee.GetAllEmployeesRequest
	3,  // 5: employee.EmployeeService.SearchEmployees:input_type -> employee.SearchEmployeesRequest
	5,  // 6: employee.EmployeeService.GetEmployeeCredentials:input_type -> employee.GetEmployeeCredentialsRequest
	7,  // 7: employee.EmployeeService.CreateEmployee:input_type -> employee.CreateEmployeeRequest
	9,  // 8: employee.EmployeeService.GetEmployeeById:input_type -> employee.GetEmployeeByIdRequest
	2,  // 9: employee.EmployeeService.GetAllEmployees:output_type -> employee.GetAllEmployeesResponse
	4,  // 10: employee.EmployeeService.SearchEmployees:output_type -> employee.SearchEmployeesResponse
	6,  // 11: employee.EmployeeService.GetEmployeeCredentials:output_type -> employee.GetEmployeeCredentialsResponse
	8,  // 12: employee.EmployeeService.CreateEmployee:output_type -> employee.CreateEmployeeResponse
	10, // 13: employee.EmployeeService.GetEmployeeById:output_type -> employee.GetEmployeeByIdResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_employee_proto_init() }
func file_employee_proto_init() {
	if File_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_proto_rawDesc), len(file_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_proto_goTypes,
		DependencyIndexes: file_employee_proto_depIdxs,
		MessageInfos:      file_employee_proto_msgTypes,
	}.Build()
	File_employee_proto = out.File
	file_employee_proto_goTypes = nil
	file_employee_proto_depIdxs = nil
}
