// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: loan.proto

package loan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoanService_GetClientLoans_FullMethodName         = "/loan.LoanService/GetClientLoans"
	LoanService_GetLoanDetails_FullMethodName         = "/loan.LoanService/GetLoanDetails"
	LoanService_GetLoanInstallments_FullMethodName    = "/loan.LoanService/GetLoanInstallments"
	LoanService_SubmitLoanApplication_FullMethodName  = "/loan.LoanService/SubmitLoanApplication"
	LoanService_ApproveLoan_FullMethodName            = "/loan.LoanService/ApproveLoan"
	LoanService_RejectLoan_FullMethodName             = "/loan.LoanService/RejectLoan"
	LoanService_GetAllLoanApplications_FullMethodName = "/loan.LoanService/GetAllLoanApplications"
	LoanService_GetAllLoans_FullMethodName            = "/loan.LoanService/GetAllLoans"
)

// LoanServiceClient is the client API for LoanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoanServiceClient interface {
	GetClientLoans(ctx context.Context, in *GetClientLoansRequest, opts ...grpc.CallOption) (*GetClientLoansResponse, error)
	GetLoanDetails(ctx context.Context, in *GetLoanDetailsRequest, opts ...grpc.CallOption) (*GetLoanDetailsResponse, error)
	GetLoanInstallments(ctx context.Context, in *GetLoanInstallmentsRequest, opts ...grpc.CallOption) (*GetLoanInstallmentsResponse, error)
	SubmitLoanApplication(ctx context.Context, in *SubmitLoanApplicationRequest, opts ...grpc.CallOption) (*SubmitLoanApplicationResponse, error)
	ApproveLoan(ctx context.Context, in *ApproveLoanRequest, opts ...grpc.CallOption) (*ApproveLoanResponse, error)
	RejectLoan(ctx context.Context, in *RejectLoanRequest, opts ...grpc.CallOption) (*RejectLoanResponse, error)
	GetAllLoanApplications(ctx context.Context, in *GetAllLoanApplicationsRequest, opts ...grpc.CallOption) (*GetAllLoanApplicationsResponse, error)
	GetAllLoans(ctx context.Context, in *GetAllLoansRequest, opts ...grpc.CallOption) (*GetAllLoansResponse, error)
}

type loanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanServiceClient(cc grpc.ClientConnInterface) LoanServiceClient {
	return &loanServiceClient{cc}
}

func (c *loanServiceClient) GetClientLoans(ctx context.Context, in *GetClientLoansRequest, opts ...grpc.CallOption) (*GetClientLoansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientLoansResponse)
	err := c.cc.Invoke(ctx, LoanService_GetClientLoans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoanDetails(ctx context.Context, in *GetLoanDetailsRequest, opts ...grpc.CallOption) (*GetLoanDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoanDetailsResponse)
	err := c.cc.Invoke(ctx, LoanService_GetLoanDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoanInstallments(ctx context.Context, in *GetLoanInstallmentsRequest, opts ...grpc.CallOption) (*GetLoanInstallmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoanInstallmentsResponse)
	err := c.cc.Invoke(ctx, LoanService_GetLoanInstallments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) SubmitLoanApplication(ctx context.Context, in *SubmitLoanApplicationRequest, opts ...grpc.CallOption) (*SubmitLoanApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitLoanApplicationResponse)
	err := c.cc.Invoke(ctx, LoanService_SubmitLoanApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ApproveLoan(ctx context.Context, in *ApproveLoanRequest, opts ...grpc.CallOption) (*ApproveLoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveLoanResponse)
	err := c.cc.Invoke(ctx, LoanService_ApproveLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) RejectLoan(ctx context.Context, in *RejectLoanRequest, opts ...grpc.CallOption) (*RejectLoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectLoanResponse)
	err := c.cc.Invoke(ctx, LoanService_RejectLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetAllLoanApplications(ctx context.Context, in *GetAllLoanApplicationsRequest, opts ...grpc.CallOption) (*GetAllLoanApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllLoanApplicationsResponse)
	err := c.cc.Invoke(ctx, LoanService_GetAllLoanApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetAllLoans(ctx context.Context, in *GetAllLoansRequest, opts ...grpc.CallOption) (*GetAllLoansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllLoansResponse)
	err := c.cc.Invoke(ctx, LoanService_GetAllLoans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanServiceServer is the server API for LoanService service.
// All implementations must embed UnimplementedLoanServiceServer
// for forward compatibility.
type LoanServiceServer interface {
	GetClientLoans(context.Context, *GetClientLoansRequest) (*GetClientLoansResponse, error)
	GetLoanDetails(context.Context, *GetLoanDetailsRequest) (*GetLoanDetailsResponse, error)
	GetLoanInstallments(context.Context, *GetLoanInstallmentsRequest) (*GetLoanInstallmentsResponse, error)
	SubmitLoanApplication(context.Context, *SubmitLoanApplicationRequest) (*SubmitLoanApplicationResponse, error)
	ApproveLoan(context.Context, *ApproveLoanRequest) (*ApproveLoanResponse, error)
	RejectLoan(context.Context, *RejectLoanRequest) (*RejectLoanResponse, error)
	GetAllLoanApplications(context.Context, *GetAllLoanApplicationsRequest) (*GetAllLoanApplicationsResponse, error)
	GetAllLoans(context.Context, *GetAllLoansRequest) (*GetAllLoansResponse, error)
	mustEmbedUnimplementedLoanServiceServer()
}

// UnimplementedLoanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoanServiceServer struct{}

func (UnimplementedLoanServiceServer) GetClientLoans(context.Context, *GetClientLoansRequest) (*GetClientLoansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientLoans not implemented")
}
func (UnimplementedLoanServiceServer) GetLoanDetails(context.Context, *GetLoanDetailsRequest) (*GetLoanDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoanDetails not implemented")
}
func (UnimplementedLoanServiceServer) GetLoanInstallments(context.Context, *GetLoanInstallmentsRequest) (*GetLoanInstallmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoanInstallments not implemented")
}
func (UnimplementedLoanServiceServer) SubmitLoanApplication(context.Context, *SubmitLoanApplicationRequest) (*SubmitLoanApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitLoanApplication not implemented")
}
func (UnimplementedLoanServiceServer) ApproveLoan(context.Context, *ApproveLoanRequest) (*ApproveLoanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveLoan not implemented")
}
func (UnimplementedLoanServiceServer) RejectLoan(context.Context, *RejectLoanRequest) (*RejectLoanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectLoan not implemented")
}
func (UnimplementedLoanServiceServer) GetAllLoanApplications(context.Context, *GetAllLoanApplicationsRequest) (*GetAllLoanApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllLoanApplications not implemented")
}
func (UnimplementedLoanServiceServer) GetAllLoans(context.Context, *GetAllLoansRequest) (*GetAllLoansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllLoans not implemented")
}
func (UnimplementedLoanServiceServer) mustEmbedUnimplementedLoanServiceServer() {}
func (UnimplementedLoanServiceServer) testEmbeddedByValue()                     {}

// UnsafeLoanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanServiceServer will
// result in compilation errors.
type UnsafeLoanServiceServer interface {
	mustEmbedUnimplementedLoanServiceServer()
}

func RegisterLoanServiceServer(s grpc.ServiceRegistrar, srv LoanServiceServer) {
	// If the following call panics, it indicates UnimplementedLoanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoanService_ServiceDesc, srv)
}

func _LoanService_GetClientLoans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientLoansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetClientLoans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetClientLoans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetClientLoans(ctx, req.(*GetClientLoansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoanDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoanDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetLoanDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoanDetails(ctx, req.(*GetLoanDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoanInstallments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanInstallmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoanInstallments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetLoanInstallments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoanInstallments(ctx, req.(*GetLoanInstallmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_SubmitLoanApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitLoanApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).SubmitLoanApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_SubmitLoanApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).SubmitLoanApplication(ctx, req.(*SubmitLoanApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ApproveLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ApproveLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ApproveLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ApproveLoan(ctx, req.(*ApproveLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_RejectLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).RejectLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_RejectLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).RejectLoan(ctx, req.(*RejectLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetAllLoanApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllLoanApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetAllLoanApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetAllLoanApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetAllLoanApplications(ctx, req.(*GetAllLoanApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetAllLoans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllLoansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetAllLoans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetAllLoans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetAllLoans(ctx, req.(*GetAllLoansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanService_ServiceDesc is the grpc.ServiceDesc for LoanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loan.LoanService",
	HandlerType: (*LoanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientLoans",
			Handler:    _LoanService_GetClientLoans_Handler,
		},
		{
			MethodName: "GetLoanDetails",
			Handler:    _LoanService_GetLoanDetails_Handler,
		},
		{
			MethodName: "GetLoanInstallments",
			Handler:    _LoanService_GetLoanInstallments_Handler,
		},
		{
			MethodName: "SubmitLoanApplication",
			Handler:    _LoanService_SubmitLoanApplication_Handler,
		},
		{
			MethodName: "ApproveLoan",
			Handler:    _LoanService_ApproveLoan_Handler,
		},
		{
			MethodName: "RejectLoan",
			Handler:    _LoanService_RejectLoan_Handler,
		},
		{
			MethodName: "GetAllLoanApplications",
			Handler:    _LoanService_GetAllLoanApplications_Handler,
		},
		{
			MethodName: "GetAllLoans",
			Handler:    _LoanService_GetAllLoans_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loan.proto",
}
